# render.yaml
services:
  - type: web
    name: onlyz
    env: python
    plan: free
    region: frankfurt
    
    buildCommand: |
      pip install -r requirements.txt
      python -c "
      from app import app, db
      with app.app_context():
          print('🔧 Création des tables...')
          db.create_all()
          print('✅ Base de données initialisée avec succès')
      "
    
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    
    envVars:
      - key: FLASK_APP
        value: app.py