# Render blueprint for OnlyZ (Flask app)
# Les variables sensibles (mot de passe, secret, etc.) sont définies ici mais doivent idéalement
# être ajoutées directement dans le dashboard Render pour plus de sécurité.

services:
  - type: web
    name: onlyz-web
    env: python
    branch: main
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade || python -c "from app import app, db; app.app_context().push(); db.create_all()"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: SESSION_SECRET
        value: your_session_secret_here
      - key: DATABASE_URL
        value:your_database_url_here
      - key: PORT
        value: 3000
      - key: PGDATABASE
        value: your_database_name_here
      - key: PGUSER
        value: your_database_user_here
      - key: PGPASSWORD
        value: yourpgpassword_here
      - key: PGHOST
        value: yourpg_host_here
      - key: PGPORT
        value: 5432
      - key: ADMIN_PASSWORD
        value:your_admin_password_here


databases:
  - name: onlyZ
    plan: starter
    region: oregon
    databaseName: onlyz


